Repository Pyragas/tool-rent, pull requests merged in 2021-05, with the labels that each got.

#47 Fix/remove item entity
  src/main/java/com/psk/pyragas/ToolRent/dao/ItemsDAO.java
  src/main/java/com/psk/pyragas/ToolRent/entities/Advertisement.java
  src/main/java/com/psk/pyragas/ToolRent/entities/Chat.java
  src/main/java/com/psk/pyragas/ToolRent/entities/Item.java
  src/main/java/com/psk/pyragas/ToolRent/entities/LegalPerson.java
  src/main/java/com/psk/pyragas/ToolRent/entities/Message.java
  src/main/java/com/psk/pyragas/ToolRent/entities/NaturalPerson.java
  src/main/java/com/psk/pyragas/ToolRent/entities/Order.java
  src/main/java/com/psk/pyragas/ToolRent/entities/Photo.java
  src/main/java/com/psk/pyragas/ToolRent/entities/Profile.java
  src/main/java/com/psk/pyragas/ToolRent/usecases/AddItem.java
  src/main/java/com/psk/pyragas/ToolRent/usecases/CreateAdvertisement.java
  src/main/java/com/psk/pyragas/ToolRent/usecases/ExampleItem.java
  src/main/java/com/psk/pyragas/ToolRent/usecases/Login.java
  src/main/java/com/psk/pyragas/ToolRent/utils/MockData.java
Labels: good first issue, help wanted

#46 Feature/profile 185 mk
  src/main/java/com/psk/pyragas/ToolRent/usecases/EditProfile.java
  src/main/java/com/psk/pyragas/ToolRent/usecases/MyProfile.java
  src/main/webapp/edit_profile.xhtml
  src/main/webapp/my_profile.xhtml
  src/main/webapp/templates/navbar.xhtml
Labels: can we merge?, question

#50 Fix/null selected add
  src/main/java/com/psk/pyragas/ToolRent/entities/Order.java
  src/main/java/com/psk/pyragas/ToolRent/usecases/Advertisements.java
  src/main/webapp/advertisements.xhtml
Labels: question
